    SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure BOOKING_TYPE_CREATION is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='create table BOOKING_TYPE_DB(  
                    bkng_typ_id NUMBER GENERATED BY DEFAULT AS IDENTITY ,  
                    bkng_typ varchar2(20) unique NOT NULL,
                    constraint pk_bkng_tp_id primary key (bkng_typ_id)  
                    )';
                    
       EXECUTE IMMEDIATE table_name;
    end BOOKING_TYPE_CREATION;
    /
    
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            SELECT count(*) into nCount FROM user_tables where table_name = 'BOOKING_TYPE_DB';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE TABLE_NAME ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 BOOKING_TYPE_CREATION;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE TABLE_NAME CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 BOOKING_TYPE_CREATION;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_Booking_Type_DB(bkng_typ_name in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into BOOKING_TYPE_DB(bkng_typ) values (bkng_typ_name);
             dbms_output.put_line('Row inserted at BOOKING_TYPE_DB table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                when others then
                    dbms_output.put_line('Error while inserting data in BOOKING_TYPE_DB Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_Booking_Type_DB;
     /
    
    SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure BOOKING_TYPE_CREATION is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='create table BOOKING_TYPE_DB(  
                    bkng_typ_id NUMBER GENERATED BY DEFAULT AS IDENTITY ,  
                    bkng_typ varchar2(20) unique NOT NULL,
                    constraint pk_bkng_tp_id primary key (bkng_typ_id)  
                    )';
                    
       EXECUTE IMMEDIATE table_name;
    end BOOKING_TYPE_CREATION;
    /
    
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            SELECT count(*) into nCount FROM user_tables where table_name = 'BOOKING_TYPE_DB';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE TABLE_NAME ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 BOOKING_TYPE_CREATION;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE TABLE_NAME CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 BOOKING_TYPE_CREATION;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_Booking_Type_DB(bkng_typ_name in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into BOOKING_TYPE_DB(bkng_typ) values (bkng_typ_name);
             dbms_output.put_line('Row inserted at BOOKING_TYPE_DB table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in BOOKING_TYPE_DB Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_Booking_Type_DB;
     /
    
    execute insrt_Booking_Type_DB('INTERNET');
    execute insrt_Booking_Type_DB('WALK-IN');
    execute insrt_Booking_Type_DB('REFERRAL');
    
    --select * from BOOKING_TYPE_DB ;

    
select * from BOOKING_TYPE_DB ;