SET SERVEROUTPUT ON;

---------------------------------------------------- LOCATION TABLE  -------------------------------------------
    -- TABLE CREATION PROCEDURE
    create or replace procedure location_creation is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE LOCATION(
                            LOCATION_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            STATE VARCHAR(8) NOT NULL,
                            CITY VARCHAR(50),
                            ZIPCODE VARCHAR(5) NOT NULL UNIQUE,
                            constraint pk_loc_id PRIMARY KEY(LOCATION_ID)
                    )';
       EXECUTE IMMEDIATE table_name;
    end location_creation;
    /
    
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='LOCATION';
            SELECT count(*) into nCount FROM user_tables where table_name = 'LOCATION';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name ||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 location_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE ' ||table_name ||' CREATED');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 location_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_location(state_name in varchar, city_name in varchar, zipcode in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into  LOCATION(state, city, zipcode) values (state_name, city_name, zipcode);
             dbms_output.put_line('Row inserted at Location table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in Location Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_location;
     /
    
    execute insrt_location('MA','Boston','02115');
    execute insrt_location('TX','DALLAS','04567');
    execute insrt_location('CA','SAN JOSE','08921');
    execute insrt_location('NY','NY CITY','01209');
    
    select * from LOCATION;

    ---------------------------------------------------- HOTEL TABLE  -------------------------------------------

    -- TABLEC REATION PROCEDURE
    create or replace procedure hotel_creation is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE HOTEL(
                            HOTEL_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            HOTEL_NAME VARCHAR2(255) NOT NULL UNIQUE,
                            LOCATION_ID NUMBER,
                            RATING VARCHAR2(50),
                            constraint pk_htl_id PRIMARY KEY(HOTEL_ID),
                            constraint fk_loc_id FOREIGN KEY(LOCATION_ID) REFERENCES location (location_id)
                           
                    )';
       EXECUTE IMMEDIATE table_name;
    end hotel_creation;
    /
    
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='HOTEL';
            SELECT count(*) into nCount FROM user_tables where table_name = 'HOTEL';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name ||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 hotel_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE' ||table_name ||' CREATED');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 hotel_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_hotel(hotel_name in varchar, location_id_name in number, rating in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into  HOTEL(HOTEL_NAME, LOCATION_ID, RATING) values (hotel_name, location_id_name, rating);
             dbms_output.put_line('Row inserted at HOTEL table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in Location Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_hotel;
     /
    
    execute insrt_hotel('Hyatt Regency',1,'3 Star');
    execute insrt_hotel('Hyatt Grand',2,'4 Star');
    execute insrt_hotel('Andaz West Hollywood',3,'3 Star');
    execute insrt_hotel('Grand Hyatt DFW',4,'3 Star');

    select * from hotel;

    ---------------------------------------------------- DISCOUNT TABLE  -------------------------------------------

 -- TABLE CREATION PROCEDURE
    create or replace procedure discount_creation is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE DISCOUNT(
                            disc_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            disc_value NUMBER NOT NULL UNIQUE,
                            constraint pk_discount_id PRIMARY KEY(disc_id)
                    )';
       EXECUTE IMMEDIATE table_name;
    end discount_creation;
    /
    
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='DISCOUNT';
            SELECT count(*) into nCount FROM user_tables where table_name = 'DISCOUNT';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 discount_creation;
                end;    
             DBMS_OUTPUT.PUT_LINE('TABLE '||table_name||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 discount_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_discount(disc_value_name in number)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into DISCOUNT(disc_value) values (disc_value_name);
             dbms_output.put_line('Row inserted at Discount table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in Location Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_discount;
     /
    
    execute insrt_discount(10);
    execute insrt_discount(15);
    execute insrt_discount(20);
    execute insrt_discount(30);
    execute insrt_discount(40);
    execute insrt_discount(50);
    
    select * from discount;