    SET SERVEROUTPUT ON;
    

    -- TABLEC REATION PROCEDURE
    create or replace procedure discount_creation is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE DISCOUNT_DB(
                            disc_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            disc_value NUMBER NOT NULL UNIQUE,
                            PRIMARY KEY(disc_id)
                    )';
       EXECUTE IMMEDIATE table_name;
    end discount_creation;
    /
    
      DECLARE
      
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='DISCOUNT_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = 'DISCOUNT_DB';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 discount_creation;
                end;    
             DBMS_OUTPUT.PUT_LINE('TABLE '||table_name||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 discount_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_discount_db(disc_value_name in number)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into DISCOUNT_DB(disc_value) values (disc_value_name);
             dbms_output.put_line('Row inserted at Location table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                when others then
                    dbms_output.put_line('Error while inserting data in Location Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_discount_db;
     /
    
    execute insrt_discount_db(0);
    execute insrt_discount_db(10);
    
    select * from discount_db;