  
  SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure GUEST_creation is table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='create table guest_DB(  
                    guest_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,  
                    guest_name varchar2(50) NOT NULL,
                    DOB date NOT NULL,
                    ph_num varchar2(16) NOT NULL,
                    email varchar2(255),
                    mem_id varchar(8),
                    vip_status varchar(8),
                    gender varchar(8) NOT NULL,
                    prf_id  varchar2(8),
                    primary key (guest_id),
                    constraint unique_PHONE UNIQUE (PH_NUM),
                    FOREIGN KEY (prf_id) REFERENCES preference(prf_id),
                    FOREIGN KEY (mem_id) REFERENCES member(mem_id),
                    CHECK(REGEXP_LIKE(EMAIL,''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'')),
                    CHECK(REGEXP_LIKE(PH_NUM,''^[0-9]{10}$''))
                    )';
       EXECUTE IMMEDIATE table_name;
    end GUEST_creation;
    /
    
      DECLARE
            tname varchar2(50);
            nCount NUMBER;
        BEGIN
            TNAME:='GUEST_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = TNAME;
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '||TNAME || ' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 GUEST_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE ' || TNAME ||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('Table '||TNAME ||' doesnt exits! So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 GUEST_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
    create or replace procedure insrt_GUEST(GUEST_NAME in varchar,DOB IN DATE, PH_NUM IN VARCHAR, EMAIL IN VARCHAR2,MEM_ID IN NUMBER, VIP_STATUS IN VARCHAR,GENDER IN VARCHAR, PRF_ID IN VARCHAR)
         as
          begin
          
                 dbms_output.put_line('----------------------------------------------------------');
                insert into GUEST_DB(GUEST_NAME  ,DOB  , PH_NUM  , EMAIL,MEM_ID, VIP_STATUS,GENDER, PRF_ID) values (GUEST_NAME  ,DOB  , PH_NUM  , EMAIL,MEM_ID, VIP_STATUS,GENDER, PRF_ID);
             dbms_output.put_line('Row inserted at GUEST table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oops! This record already exists');
                when others then
                    dbms_output.put_line('Error while inserting data in GUEST Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_GUEST;
     /
    
    execute insrt_GUEST('PUJA','24 MAY 1996','9851024784','PUZA@GMAIL.COM',1,'VIP-1','FEMALE',1);
    execute insrt_GUEST('ABC',SYSDATE,'9851079784','PUZA@GMAIL.COM',1,'VIP-1','FEMALE',1);
--SELECT * FROM GUEST_DB;
 