SET SERVEROUTPUT ON;
    -- TABLEC REATION PROCEDURE
    create or replace procedure hotel_creation is
    table_name varchar2(4000);
   
   
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE HOTEL_DB(
                            HOTEL_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            HOTEL_NAME VARCHAR2(255) NOT NULL UNIQUE,
                            LOCATION_ID NUMBER,
                            RATING VARCHAR2(50),
                            constraint pk_htl_id PRIMARY KEY(HOTEL_ID),
                            constraint fk_loc_id FOREIGN KEY(LOCATION_ID) REFERENCES location_db (location_id)
                           
                    )';
       EXECUTE IMMEDIATE table_name;
    end hotel_creation;
    /
    
    
   
      DECLARE
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='HOTEL_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = 'HOTEL_DB';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name ||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 hotel_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE ' ||table_name ||' CREATED');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 hotel_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_hotel_db(hotel_name in varchar, location_id_name in number, rating in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into  HOTEL_DB(HOTEL_NAME, LOCATION_ID, RATING) values (hotel_name, location_id_name, rating);
             dbms_output.put_line('Row inserted at HOTEL table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in Location Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_hotel_db;
     /
    
    execute insrt_hotel_db('Hyatt Regency',1,'3 Star');
    execute insrt_hotel_db('Hyatt Grand',2,'4 Star');

    
    select * from hotel_db;
    
    