    SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure preferences_creation is
        table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='create table PREFERENCES_DB(  
  prf_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,  
  preferences varchar2(255) NOT NULL,
primary key (prf_id)  
  )';
    EXECUTE IMMEDIATE table_name;
    end preferences_creation;
    /
    
 -- Drop table preferences_db;  
    
  DECLARE
        tname varchar2(50);
        nCount NUMBER;
    BEGIN
        SELECT count(*) into nCount FROM user_tables where table_name = 'PREFERENCES_DB';
        IF(nCount > 0)
        
        THEN
                DBMS_OUTPUT.PUT_LINE('TABLE PREFERENCES_DB ALREADY EXISTS.');
          
        ELSE
        
        -- call to table creation stored procedure 
            begin 
             preferences_creation;
                     DBMS_OUTPUT.PUT_LINE('TABLE PREFERENCES_DB CREATED.');     

            end;    
   
        END IF;
        exception 
          when no_data_found then
           dbms_output.put_line('table doesnt exits!, So we created one');
           
           -- call to table creation stored procedure 
           begin 
             preferences_creation;
            end; 
            
            when others
                then
                dbms_output.put_line('Something went wrong!');
                dbms_output.put_line(dbms_utility.format_error_stack);
END;
/  
  

create or replace procedure insrt_preferences_db(preferences_name in varchar)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into PREFERENCES_DB(preferences) values (preferences_name);
             dbms_output.put_line('Row inserted at Location table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                when others then
                    dbms_output.put_line('Error while inserting data in PREFERENCES Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_preferences_db;
     /
    
    execute insrt_preferences_db('Guest loves to smoke');
    execute insrt_preferences_db('Guests Need newspaper every Morning');
    execute insrt_preferences_db('Guest is allergic to pets');
    execute insrt_preferences_db('Guest wants rooms with windows facing the pool');
    
    select * from PREFERENCES_DB;