    SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure room_availability_creation is
    table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE ROOM_AVAILABILITY_DB(
                            ROOM_AVL_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ROOM_STS_ID  NUMBER NOT NULL,
                            IS_AVAILABLE VARCHAR2(50) NOT NULL,
                            STAFF_ID NUMBER NOT NULL,
                            AVL_TIME_STAMP TIMESTAMP NOT NULL,
                            constraint pk_room_avl_id PRIMARY KEY(ROOM_AVL_ID),
                            constraint fk_room_sts_id FOREIGN KEY(ROOM_STS_ID) REFERENCES room_status_db (room_sts_id),
                            constraint fk_staff_id FOREIGN KEY(STAFF_ID) REFERENCES staff_db (staff_id)
                    )';
       EXECUTE IMMEDIATE table_name;
    end room_availability_creation;
    /
    
      DECLARE
      
            table_name varchar2(50);
            nCount NUMBER;
        BEGIN
            table_name:='ROOM_AVAILABILITY_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = 'ROOM_AVAILABILITY_DB';
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '|| table_name||' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 room_availability_creation;
                end;    
             DBMS_OUTPUT.PUT_LINE('TABLE '||table_name||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 room_availability_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_room_availability_db(room_sts_id_name in number,is_avail in varchar,staff_id in number,avl_timestamp in timestamp)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into ROOM_AVAILABILITY_DB(ROOM_STS_ID,IS_AVAILABLE,STAFF_ID,AVL_TIME_STAMP) values (room_sts_id_name,is_avail,staff_id,avl_timestamp);
             dbms_output.put_line('Row inserted at Room-Availability table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
                WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                rollback;
                when others then
                    dbms_output.put_line('Error while inserting data in Room-Availability Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_room_availability_db;
     /
    
    execute insrt_room_availability_db(1,'Available',3,TO_DATE('2021/05/11 23:59:59', 'yyyy/mm/dd hh24:mi:ss'));
    execute insrt_room_availability_db(2,'Not Available',4,TO_DATE('2021/05/19 23:59:59','yyyy/mm/dd hh24:mi:ss'));
    execute insrt_room_availability_db(3,'Not Available',5,TO_DATE('2021/06/11 23:59:59', 'yyyy/mm/dd hh24:mi:ss'));
    execute insrt_room_availability_db(4,'Available',6,TO_DATE('2021/05/05 23:59:59', 'yyyy/mm/dd hh24:mi:ss'));
    execute insrt_room_availability_db(5,'Not Available',7,TO_DATE('2021/05/25 23:59:59', 'yyyy/mm/dd hh24:mi:ss'));
    
select * from room_availability_db;
