  SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure ROOM_creation is table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='create table ROOM_DB(
                    ROOM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    ROOM_TYP_ID NUMBER ,
                    ROOM_AVL_ID NUMBER,
                    ROOM_LVL NUMBER,
                    AMENITY_ID NUMBER,
                    HOTEL_ID NUMBER,
                    PRIMARY KEY (ROOM_ID),
                    FOREIGN KEY (ROOM_TYP_ID) REFERENCES ROOM_TYPE_DB(ROOM_TYP_ID),
                    FOREIGN KEY (ROOM_AVL_ID) REFERENCES ROOM_AVAILABILITY_DB(ROOM_AVL_ID),
                    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL_DB(HOTEL_ID),
                    FOREIGN KEY (AMENITY_ID) REFERENCES AMENITY_DB(AMENITY_ID)
                    )';
                    
       EXECUTE IMMEDIATE table_name;
    end ROOM_creation;
    /
    
      DECLARE
            tname varchar2(50);
            nCount NUMBER;
        BEGIN
            TNAME:='ROOM_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = TNAME;
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '||TNAME || ' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 ROOM_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE ' || TNAME ||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('Table '||TNAME ||' doesnt exits! So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 ROOM_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
    create or replace procedure insrt_ROOM(ROOM_TYP_ID IN NUMBER ,ROOM_AVL_ID  IN NUMBER, ROOM_LVL IN NUMBER,AMENITY_ID IN NUMBER ,HOTEL_ID IN NUMBER)
         as
          begin
          
                 dbms_output.put_line('----------------------------------------------------------');
                insert into ROOM_DB(ROOM_TYP_ID  ,ROOM_AVL_ID  , ROOM_LVL,AMENITY_ID,HOTEL_ID) values (ROOM_TYP_ID  ,ROOM_AVL_ID  , ROOM_LVL,AMENITY_ID,HOTEL_ID);
             dbms_output.put_line('Row inserted at ROOM table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oops! This record already exists');
                ROLLBACK;
                when others then
                    dbms_output.put_line('Error while inserting data in Room Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_ROOM;
     /

 