SET SERVEROUTPUT ON;
    
    -- TABLEC REATION PROCEDURE
    create or replace procedure STAFF_creation is table_name varchar2(4000);
    BEGIN
    -- table creation query
       table_name:='create table STAFF(
                    STAFF_ID VARCHAR(8) NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    DESG_ID VARCHAR(8) NOT NULL,
                    STAFF_NAME VARCHAR(50) NOT NULL,
                    USR_NM VARCHAR(50) NOT NULL,
                    PASS VARCHAR(50) NOT NULL,
                    DISC_ID NUMBER NOT NULL,
                    DEPT_ID NUMBER NOT NULL,
                    HOTEL_ID NUMBER NOT NULL,
                    primary key(STAFF_ID),
                    FOREIGN key(DESG_ID)REFERENCES DESIGNATION(DESG_ID) ON DELETE CASCADE,
                    FOREIGN key(DISC_ID)REFERENCES DISCOUNT(DISC_ID) ON DELETE CASCADE,
                    FOREIGN key(DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE, 
                    FOREIGN key(HOTEL_ID)REFERENCES HOTEL(HOTEL_ID) ON DELETE CASCADE
                    )';
       EXECUTE IMMEDIATE table_name;
    end STAFF_creation;
    /
    
      DECLARE
            tname varchar2(50);
            nCount NUMBER;
        BEGIN
            TNAME := 'STAFF_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = TNAME;
            IF(nCount > 0)
            
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE STAFF ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 STAFF_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE STAFF CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('table doesnt exits!, So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 STAFF_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
     create or replace procedure insrt_STAFF(DESG_ID in varchar, STAFF_NAME in varchar, USR_NM in varchar,PASS in varchar,DISC_ID IN NUMBER,DEPT_ID IN NUMBER, HOTEL_ID IN NUMBER)
         as
          begin
                 dbms_output.put_line('----------------------------------------------------------');
                insert into STAFF_DB(DESG_ID, STAFF_NAME, USR_NM,PASS, DISC_ID,HOTEL_ID) values (DESG_ID, STAFF_NAME, USR_NM,PASS, DISC_ID,HOTEL_ID);
             dbms_output.put_line('Row inserted at STAFF table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
            then
            dbms_output.put_line('OOPS! DUPLICATE VALUE FOUND');
                when others then
                    dbms_output.put_line('Error while inserting data in STAFF Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');

            end insrt_STAFF;
     /
    
    execute insrt_STAFF('MANAGER','JOHN','JHN','JH',12,1);
    
    select * from STAFF_db;
 