  SET SERVEROUTPUT ON;
    
    -- TABLE CREATION PROCEDURE
    create or replace procedure Staff_avail_creation is table_name varchar2(4000);
   
    BEGIN
    -- table creation query
       table_name:='CREATE TABLE STAFF_AVAIL_DB(STAFF_AVL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, 
                    STAFF_ID NUMBER NOT NULL,
                    STAFF_STATUS VARCHAR(20) NOT NULL,
                    STAFF_AVL_DT_TIME TIMESTAMP NOT NULL,
                    PRIMARY KEY (STAFF_AVL_ID),
                    FOREIGN KEY (STAFF_ID) REFERENCES STAFF_DB(STAFF_ID))';
       EXECUTE IMMEDIATE table_name;
    end Staff_avail_creation;
    /
    
      DECLARE
            tname varchar2(50);
            nCount NUMBER;
        BEGIN
            tname:='STAFF_AVAIL_DB';
            SELECT count(*) into nCount FROM user_tables where table_name = tname;
            IF(nCount > 0)
             
            THEN
                    DBMS_OUTPUT.PUT_LINE('TABLE '||TNAME || ' ALREADY EXISTS.');
            ELSE
            -- call to table creation stored procedure 
                begin 
                 Staff_avail_creation;
                end;    
            DBMS_OUTPUT.PUT_LINE('TABLE ' || TNAME ||' CREATED.');
            
            END IF;
            exception 
              when no_data_found then
               dbms_output.put_line('Table '||TNAME ||' doesnt exits! So we created one');
               
               -- call to table creation stored procedure 
               begin 
                 Staff_avail_creation;
                end; 
                
                when others
                    then
                    dbms_output.put_line('Something went wrong!');
                    dbms_output.put_line(dbms_utility.format_error_stack);
    END;
    /  
    
    create or replace procedure insrt_STAFF_AVAIL(STAFF_ID in varchar,STAFF_STATUS IN varchar, STAFF_AVL_DT_TIME IN date)
    AS
          begin
          
                 dbms_output.put_line('----------------------------------------------------------');
                insert into STAFF_AVAIL_DB(STAFF_ID,STAFF_STATUS,STAFF_AVL_DT_TIME) values (STAFF_ID,STAFF_STATUS,STAFF_AVL_DT_TIME);
             dbms_output.put_line('Row inserted at STAFF_AVAIL table');
                 dbms_output.put_line('----------------------------------------------------------');
            commit;
            exception
            WHEN DUP_VAL_ON_INDEX
                then
                dbms_output.put_line('Oop! This record already exists');
                ROLLBACK;
                when others then
                    dbms_output.put_line('Error while inserting data in GUEST Table');
                    rollback;
                    dbms_output.put_line('The error encountered is: ');
                    dbms_output.put_line(dbms_utility.format_error_stack);
                    dbms_output.put_line('----------------------------------------------------------');
            end insrt_STAFF_AVAIL;
     /
    
    execute insrt_STAFF_AVAIL(3,'LEAVE',SYSDATE);

